### ISSUE TITLE
0.2 update

### ISSUE THREAD

**Issue by rachmadaniHaryono** [rachmadaniHaryono/python-mal#12]
- [ ] merging all old issue from upstream and this fork
  - [ ] https://github.com/shaldengeki/python-mal/issues/11 Scrap is absolutely broken
  - [ ] https://github.com/shaldengeki/python-mal/issues/8 Python3 could not find title div
  - [ ] https://github.com/shaldengeki/python-mal/issues/10 Python3 support
  - [ ] https://github.com/shaldengeki/python-mal/issues/7 character does not appear when parsing voice actor in anime
  - [ ] https://github.com/shaldengeki/python-mal/issues/3 Error while fetching anime info.
- [ ] fix issue on this fork
  - [ ] #11 change test runner and run coverage 
  - [ ] #10 add codeclimate integration
  - [ ] #9 add video parsing and broadcast (https://github.com/pushrbx/python-mal/commit/9da2c33)
    - [ ] video parsing
    - [ ] anime broadcast
  - [ ] #7 search feature
    - [ ] character
    - [ ] people
    - [ ] clubs
    - [ ] users
- [ ] add collaborator 
- [ ] merge with other fork
- [ ] issue on upstream to link to an active maintained project or add new person as collaborator or transfer repo

----

# change test runner and run coverage

use pytest rather than nosetest. 

see below article 

- http://stackoverflow.com/questions/22856638/nose-vs-pytest-what-are-the-subjective-differences-that-should-make-me-pick
- http://stackoverflow.com/a/5086920

for coverage pytest have [pytest-cov](https://github.com/pytest-dev/pytest-cov). use codecov for badge.
----
cc to last active fork user @pushrbx @EaterOA @kratsg
